generatorName: php
inputSpec: https://schematic-openapi-da6da39.s3.amazonaws.com/latest.yml
templateDir: templates
additionalProperties:
  artifactUrl: https://schematichq.com
  artifactVersion: 0.5.0
  composerPackageName: schematichq/schematic-php
  developerOrganization: Schematic
  developerOrganizationUrl: https://schematichq.com
  httpUserAgent: schematic-php@0.5.0
  infoEmail: engineering@schematichq.com
  infoUrl: https://schematichq.com
  invokerPackage: Schematic
  licenseName: MIT
  packageName: schematic-php
  srcBasePath: src
gitHost: github.com
gitUserId: SchematicHQ
gitRepoId: schematic-php
