<?php
/**
 * ComponentCheckoutSettings
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Schematic\Model;

use \ArrayAccess;
use \Schematic\ObjectSerializer;

/**
 * ComponentCheckoutSettings Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ComponentCheckoutSettings implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ComponentCheckoutSettings';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bundle_purchase_behavior' => '\Schematic\Model\CheckoutBundlePurchaseBehavior',
        'collect_address' => 'bool',
        'collect_email' => 'bool',
        'collect_phone' => 'bool',
        'collect_tax_id' => 'bool',
        'proration_behavior' => '\Schematic\Model\ProrationBehavior',
        'tax_collection_enabled' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bundle_purchase_behavior' => null,
        'collect_address' => null,
        'collect_email' => null,
        'collect_phone' => null,
        'collect_tax_id' => null,
        'proration_behavior' => null,
        'tax_collection_enabled' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bundle_purchase_behavior' => false,
        'collect_address' => false,
        'collect_email' => false,
        'collect_phone' => false,
        'collect_tax_id' => false,
        'proration_behavior' => false,
        'tax_collection_enabled' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bundle_purchase_behavior' => 'bundle_purchase_behavior',
        'collect_address' => 'collect_address',
        'collect_email' => 'collect_email',
        'collect_phone' => 'collect_phone',
        'collect_tax_id' => 'collect_tax_id',
        'proration_behavior' => 'proration_behavior',
        'tax_collection_enabled' => 'tax_collection_enabled'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bundle_purchase_behavior' => 'setBundlePurchaseBehavior',
        'collect_address' => 'setCollectAddress',
        'collect_email' => 'setCollectEmail',
        'collect_phone' => 'setCollectPhone',
        'collect_tax_id' => 'setCollectTaxId',
        'proration_behavior' => 'setProrationBehavior',
        'tax_collection_enabled' => 'setTaxCollectionEnabled'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bundle_purchase_behavior' => 'getBundlePurchaseBehavior',
        'collect_address' => 'getCollectAddress',
        'collect_email' => 'getCollectEmail',
        'collect_phone' => 'getCollectPhone',
        'collect_tax_id' => 'getCollectTaxId',
        'proration_behavior' => 'getProrationBehavior',
        'tax_collection_enabled' => 'getTaxCollectionEnabled'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bundle_purchase_behavior', $data ?? [], null);
        $this->setIfExists('collect_address', $data ?? [], null);
        $this->setIfExists('collect_email', $data ?? [], null);
        $this->setIfExists('collect_phone', $data ?? [], null);
        $this->setIfExists('collect_tax_id', $data ?? [], null);
        $this->setIfExists('proration_behavior', $data ?? [], null);
        $this->setIfExists('tax_collection_enabled', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bundle_purchase_behavior'] === null) {
            $invalidProperties[] = "'bundle_purchase_behavior' can't be null";
        }
        if ($this->container['collect_address'] === null) {
            $invalidProperties[] = "'collect_address' can't be null";
        }
        if ($this->container['collect_email'] === null) {
            $invalidProperties[] = "'collect_email' can't be null";
        }
        if ($this->container['collect_phone'] === null) {
            $invalidProperties[] = "'collect_phone' can't be null";
        }
        if ($this->container['collect_tax_id'] === null) {
            $invalidProperties[] = "'collect_tax_id' can't be null";
        }
        if ($this->container['proration_behavior'] === null) {
            $invalidProperties[] = "'proration_behavior' can't be null";
        }
        if ($this->container['tax_collection_enabled'] === null) {
            $invalidProperties[] = "'tax_collection_enabled' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bundle_purchase_behavior
     *
     * @return \Schematic\Model\CheckoutBundlePurchaseBehavior
     */
    public function getBundlePurchaseBehavior()
    {
        return $this->container['bundle_purchase_behavior'];
    }

    /**
     * Sets bundle_purchase_behavior
     *
     * @param \Schematic\Model\CheckoutBundlePurchaseBehavior $bundle_purchase_behavior bundle_purchase_behavior
     *
     * @return self
     */
    public function setBundlePurchaseBehavior($bundle_purchase_behavior)
    {
        if (is_null($bundle_purchase_behavior)) {
            throw new \InvalidArgumentException('non-nullable bundle_purchase_behavior cannot be null');
        }
        $this->container['bundle_purchase_behavior'] = $bundle_purchase_behavior;

        return $this;
    }

    /**
     * Gets collect_address
     *
     * @return bool
     */
    public function getCollectAddress()
    {
        return $this->container['collect_address'];
    }

    /**
     * Sets collect_address
     *
     * @param bool $collect_address collect_address
     *
     * @return self
     */
    public function setCollectAddress($collect_address)
    {
        if (is_null($collect_address)) {
            throw new \InvalidArgumentException('non-nullable collect_address cannot be null');
        }
        $this->container['collect_address'] = $collect_address;

        return $this;
    }

    /**
     * Gets collect_email
     *
     * @return bool
     */
    public function getCollectEmail()
    {
        return $this->container['collect_email'];
    }

    /**
     * Sets collect_email
     *
     * @param bool $collect_email collect_email
     *
     * @return self
     */
    public function setCollectEmail($collect_email)
    {
        if (is_null($collect_email)) {
            throw new \InvalidArgumentException('non-nullable collect_email cannot be null');
        }
        $this->container['collect_email'] = $collect_email;

        return $this;
    }

    /**
     * Gets collect_phone
     *
     * @return bool
     */
    public function getCollectPhone()
    {
        return $this->container['collect_phone'];
    }

    /**
     * Sets collect_phone
     *
     * @param bool $collect_phone collect_phone
     *
     * @return self
     */
    public function setCollectPhone($collect_phone)
    {
        if (is_null($collect_phone)) {
            throw new \InvalidArgumentException('non-nullable collect_phone cannot be null');
        }
        $this->container['collect_phone'] = $collect_phone;

        return $this;
    }

    /**
     * Gets collect_tax_id
     *
     * @return bool
     */
    public function getCollectTaxId()
    {
        return $this->container['collect_tax_id'];
    }

    /**
     * Sets collect_tax_id
     *
     * @param bool $collect_tax_id collect_tax_id
     *
     * @return self
     */
    public function setCollectTaxId($collect_tax_id)
    {
        if (is_null($collect_tax_id)) {
            throw new \InvalidArgumentException('non-nullable collect_tax_id cannot be null');
        }
        $this->container['collect_tax_id'] = $collect_tax_id;

        return $this;
    }

    /**
     * Gets proration_behavior
     *
     * @return \Schematic\Model\ProrationBehavior
     */
    public function getProrationBehavior()
    {
        return $this->container['proration_behavior'];
    }

    /**
     * Sets proration_behavior
     *
     * @param \Schematic\Model\ProrationBehavior $proration_behavior proration_behavior
     *
     * @return self
     */
    public function setProrationBehavior($proration_behavior)
    {
        if (is_null($proration_behavior)) {
            throw new \InvalidArgumentException('non-nullable proration_behavior cannot be null');
        }
        $this->container['proration_behavior'] = $proration_behavior;

        return $this;
    }

    /**
     * Gets tax_collection_enabled
     *
     * @return bool
     */
    public function getTaxCollectionEnabled()
    {
        return $this->container['tax_collection_enabled'];
    }

    /**
     * Sets tax_collection_enabled
     *
     * @param bool $tax_collection_enabled tax_collection_enabled
     *
     * @return self
     */
    public function setTaxCollectionEnabled($tax_collection_enabled)
    {
        if (is_null($tax_collection_enabled)) {
            throw new \InvalidArgumentException('non-nullable tax_collection_enabled cannot be null');
        }
        $this->container['tax_collection_enabled'] = $tax_collection_enabled;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


