<?php
/**
 * InsightsSummaryResponseData
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Schematic\Model;

use \ArrayAccess;
use \Schematic\ObjectSerializer;

/**
 * InsightsSummaryResponseData Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InsightsSummaryResponseData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InsightsSummaryResponseData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'active_credits' => 'float',
        'mrr' => '\Schematic\Model\MrrResponseData[]',
        'paid_companies' => 'int',
        'total_companies' => 'int',
        'total_features' => 'int',
        'total_plans' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'active_credits' => 'double',
        'mrr' => null,
        'paid_companies' => 'int64',
        'total_companies' => 'int64',
        'total_features' => 'int64',
        'total_plans' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'active_credits' => false,
        'mrr' => false,
        'paid_companies' => false,
        'total_companies' => false,
        'total_features' => false,
        'total_plans' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'active_credits' => 'active_credits',
        'mrr' => 'mrr',
        'paid_companies' => 'paid_companies',
        'total_companies' => 'total_companies',
        'total_features' => 'total_features',
        'total_plans' => 'total_plans'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'active_credits' => 'setActiveCredits',
        'mrr' => 'setMrr',
        'paid_companies' => 'setPaidCompanies',
        'total_companies' => 'setTotalCompanies',
        'total_features' => 'setTotalFeatures',
        'total_plans' => 'setTotalPlans'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'active_credits' => 'getActiveCredits',
        'mrr' => 'getMrr',
        'paid_companies' => 'getPaidCompanies',
        'total_companies' => 'getTotalCompanies',
        'total_features' => 'getTotalFeatures',
        'total_plans' => 'getTotalPlans'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('active_credits', $data ?? [], null);
        $this->setIfExists('mrr', $data ?? [], null);
        $this->setIfExists('paid_companies', $data ?? [], null);
        $this->setIfExists('total_companies', $data ?? [], null);
        $this->setIfExists('total_features', $data ?? [], null);
        $this->setIfExists('total_plans', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['active_credits'] === null) {
            $invalidProperties[] = "'active_credits' can't be null";
        }
        if ($this->container['mrr'] === null) {
            $invalidProperties[] = "'mrr' can't be null";
        }
        if ((count($this->container['mrr']) > 1000)) {
            $invalidProperties[] = "invalid value for 'mrr', number of items must be less than or equal to 1000.";
        }

        if ($this->container['paid_companies'] === null) {
            $invalidProperties[] = "'paid_companies' can't be null";
        }
        if ($this->container['total_companies'] === null) {
            $invalidProperties[] = "'total_companies' can't be null";
        }
        if ($this->container['total_features'] === null) {
            $invalidProperties[] = "'total_features' can't be null";
        }
        if ($this->container['total_plans'] === null) {
            $invalidProperties[] = "'total_plans' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets active_credits
     *
     * @return float
     */
    public function getActiveCredits()
    {
        return $this->container['active_credits'];
    }

    /**
     * Sets active_credits
     *
     * @param float $active_credits active_credits
     *
     * @return self
     */
    public function setActiveCredits($active_credits)
    {
        if (is_null($active_credits)) {
            throw new \InvalidArgumentException('non-nullable active_credits cannot be null');
        }
        $this->container['active_credits'] = $active_credits;

        return $this;
    }

    /**
     * Gets mrr
     *
     * @return \Schematic\Model\MrrResponseData[]
     */
    public function getMrr()
    {
        return $this->container['mrr'];
    }

    /**
     * Sets mrr
     *
     * @param \Schematic\Model\MrrResponseData[] $mrr mrr
     *
     * @return self
     */
    public function setMrr($mrr)
    {
        if (is_null($mrr)) {
            throw new \InvalidArgumentException('non-nullable mrr cannot be null');
        }

        if ((count($mrr) > 1000)) {
            throw new \InvalidArgumentException('invalid value for $mrr when calling InsightsSummaryResponseData., number of items must be less than or equal to 1000.');
        }
        $this->container['mrr'] = $mrr;

        return $this;
    }

    /**
     * Gets paid_companies
     *
     * @return int
     */
    public function getPaidCompanies()
    {
        return $this->container['paid_companies'];
    }

    /**
     * Sets paid_companies
     *
     * @param int $paid_companies paid_companies
     *
     * @return self
     */
    public function setPaidCompanies($paid_companies)
    {
        if (is_null($paid_companies)) {
            throw new \InvalidArgumentException('non-nullable paid_companies cannot be null');
        }
        $this->container['paid_companies'] = $paid_companies;

        return $this;
    }

    /**
     * Gets total_companies
     *
     * @return int
     */
    public function getTotalCompanies()
    {
        return $this->container['total_companies'];
    }

    /**
     * Sets total_companies
     *
     * @param int $total_companies total_companies
     *
     * @return self
     */
    public function setTotalCompanies($total_companies)
    {
        if (is_null($total_companies)) {
            throw new \InvalidArgumentException('non-nullable total_companies cannot be null');
        }
        $this->container['total_companies'] = $total_companies;

        return $this;
    }

    /**
     * Gets total_features
     *
     * @return int
     */
    public function getTotalFeatures()
    {
        return $this->container['total_features'];
    }

    /**
     * Sets total_features
     *
     * @param int $total_features total_features
     *
     * @return self
     */
    public function setTotalFeatures($total_features)
    {
        if (is_null($total_features)) {
            throw new \InvalidArgumentException('non-nullable total_features cannot be null');
        }
        $this->container['total_features'] = $total_features;

        return $this;
    }

    /**
     * Gets total_plans
     *
     * @return int
     */
    public function getTotalPlans()
    {
        return $this->container['total_plans'];
    }

    /**
     * Sets total_plans
     *
     * @param int $total_plans total_plans
     *
     * @return self
     */
    public function setTotalPlans($total_plans)
    {
        if (is_null($total_plans)) {
            throw new \InvalidArgumentException('non-nullable total_plans cannot be null');
        }
        $this->container['total_plans'] = $total_plans;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


