<?php
/**
 * RulesengineCompany
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Schematic\Model;

use \ArrayAccess;
use \Schematic\ObjectSerializer;

/**
 * RulesengineCompany Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RulesengineCompany implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'RulesengineCompany';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'string',
        'base_plan_id' => 'string',
        'billing_product_ids' => 'string[]',
        'credit_balances' => 'array<string,float>',
        'entitlements' => '\Schematic\Model\RulesengineFeatureEntitlement[]',
        'environment_id' => 'string',
        'id' => 'string',
        'keys' => 'array<string,string>',
        'metrics' => '\Schematic\Model\RulesengineCompanyMetric[]',
        'plan_ids' => 'string[]',
        'plan_version_ids' => 'string[]',
        'rules' => '\Schematic\Model\RulesengineRule[]',
        'subscription' => '\Schematic\Model\RulesengineSubscription',
        'traits' => '\Schematic\Model\RulesengineTrait[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => null,
        'base_plan_id' => null,
        'billing_product_ids' => null,
        'credit_balances' => null,
        'entitlements' => null,
        'environment_id' => null,
        'id' => null,
        'keys' => null,
        'metrics' => null,
        'plan_ids' => null,
        'plan_version_ids' => null,
        'rules' => null,
        'subscription' => null,
        'traits' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_id' => false,
        'base_plan_id' => true,
        'billing_product_ids' => false,
        'credit_balances' => false,
        'entitlements' => false,
        'environment_id' => false,
        'id' => false,
        'keys' => false,
        'metrics' => false,
        'plan_ids' => false,
        'plan_version_ids' => false,
        'rules' => false,
        'subscription' => false,
        'traits' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'account_id',
        'base_plan_id' => 'base_plan_id',
        'billing_product_ids' => 'billing_product_ids',
        'credit_balances' => 'credit_balances',
        'entitlements' => 'entitlements',
        'environment_id' => 'environment_id',
        'id' => 'id',
        'keys' => 'keys',
        'metrics' => 'metrics',
        'plan_ids' => 'plan_ids',
        'plan_version_ids' => 'plan_version_ids',
        'rules' => 'rules',
        'subscription' => 'subscription',
        'traits' => 'traits'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'base_plan_id' => 'setBasePlanId',
        'billing_product_ids' => 'setBillingProductIds',
        'credit_balances' => 'setCreditBalances',
        'entitlements' => 'setEntitlements',
        'environment_id' => 'setEnvironmentId',
        'id' => 'setId',
        'keys' => 'setKeys',
        'metrics' => 'setMetrics',
        'plan_ids' => 'setPlanIds',
        'plan_version_ids' => 'setPlanVersionIds',
        'rules' => 'setRules',
        'subscription' => 'setSubscription',
        'traits' => 'setTraits'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'base_plan_id' => 'getBasePlanId',
        'billing_product_ids' => 'getBillingProductIds',
        'credit_balances' => 'getCreditBalances',
        'entitlements' => 'getEntitlements',
        'environment_id' => 'getEnvironmentId',
        'id' => 'getId',
        'keys' => 'getKeys',
        'metrics' => 'getMetrics',
        'plan_ids' => 'getPlanIds',
        'plan_version_ids' => 'getPlanVersionIds',
        'rules' => 'getRules',
        'subscription' => 'getSubscription',
        'traits' => 'getTraits'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('base_plan_id', $data ?? [], null);
        $this->setIfExists('billing_product_ids', $data ?? [], null);
        $this->setIfExists('credit_balances', $data ?? [], null);
        $this->setIfExists('entitlements', $data ?? [], null);
        $this->setIfExists('environment_id', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('keys', $data ?? [], null);
        $this->setIfExists('metrics', $data ?? [], null);
        $this->setIfExists('plan_ids', $data ?? [], null);
        $this->setIfExists('plan_version_ids', $data ?? [], null);
        $this->setIfExists('rules', $data ?? [], null);
        $this->setIfExists('subscription', $data ?? [], null);
        $this->setIfExists('traits', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['account_id'] === null) {
            $invalidProperties[] = "'account_id' can't be null";
        }
        if ($this->container['billing_product_ids'] === null) {
            $invalidProperties[] = "'billing_product_ids' can't be null";
        }
        if ($this->container['credit_balances'] === null) {
            $invalidProperties[] = "'credit_balances' can't be null";
        }
        if ($this->container['environment_id'] === null) {
            $invalidProperties[] = "'environment_id' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['keys'] === null) {
            $invalidProperties[] = "'keys' can't be null";
        }
        if ($this->container['metrics'] === null) {
            $invalidProperties[] = "'metrics' can't be null";
        }
        if ($this->container['plan_ids'] === null) {
            $invalidProperties[] = "'plan_ids' can't be null";
        }
        if ($this->container['plan_version_ids'] === null) {
            $invalidProperties[] = "'plan_version_ids' can't be null";
        }
        if ($this->container['rules'] === null) {
            $invalidProperties[] = "'rules' can't be null";
        }
        if ($this->container['traits'] === null) {
            $invalidProperties[] = "'traits' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return string
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param string $account_id account_id
     *
     * @return self
     */
    public function setAccountId($account_id)
    {
        if (is_null($account_id)) {
            throw new \InvalidArgumentException('non-nullable account_id cannot be null');
        }
        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets base_plan_id
     *
     * @return string|null
     */
    public function getBasePlanId()
    {
        return $this->container['base_plan_id'];
    }

    /**
     * Sets base_plan_id
     *
     * @param string|null $base_plan_id base_plan_id
     *
     * @return self
     */
    public function setBasePlanId($base_plan_id)
    {
        if (is_null($base_plan_id)) {
            array_push($this->openAPINullablesSetToNull, 'base_plan_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('base_plan_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['base_plan_id'] = $base_plan_id;

        return $this;
    }

    /**
     * Gets billing_product_ids
     *
     * @return string[]
     */
    public function getBillingProductIds()
    {
        return $this->container['billing_product_ids'];
    }

    /**
     * Sets billing_product_ids
     *
     * @param string[] $billing_product_ids billing_product_ids
     *
     * @return self
     */
    public function setBillingProductIds($billing_product_ids)
    {
        if (is_null($billing_product_ids)) {
            throw new \InvalidArgumentException('non-nullable billing_product_ids cannot be null');
        }
        $this->container['billing_product_ids'] = $billing_product_ids;

        return $this;
    }

    /**
     * Gets credit_balances
     *
     * @return array<string,float>
     */
    public function getCreditBalances()
    {
        return $this->container['credit_balances'];
    }

    /**
     * Sets credit_balances
     *
     * @param array<string,float> $credit_balances credit_balances
     *
     * @return self
     */
    public function setCreditBalances($credit_balances)
    {
        if (is_null($credit_balances)) {
            throw new \InvalidArgumentException('non-nullable credit_balances cannot be null');
        }
        $this->container['credit_balances'] = $credit_balances;

        return $this;
    }

    /**
     * Gets entitlements
     *
     * @return \Schematic\Model\RulesengineFeatureEntitlement[]|null
     */
    public function getEntitlements()
    {
        return $this->container['entitlements'];
    }

    /**
     * Sets entitlements
     *
     * @param \Schematic\Model\RulesengineFeatureEntitlement[]|null $entitlements entitlements
     *
     * @return self
     */
    public function setEntitlements($entitlements)
    {
        if (is_null($entitlements)) {
            throw new \InvalidArgumentException('non-nullable entitlements cannot be null');
        }
        $this->container['entitlements'] = $entitlements;

        return $this;
    }

    /**
     * Gets environment_id
     *
     * @return string
     */
    public function getEnvironmentId()
    {
        return $this->container['environment_id'];
    }

    /**
     * Sets environment_id
     *
     * @param string $environment_id environment_id
     *
     * @return self
     */
    public function setEnvironmentId($environment_id)
    {
        if (is_null($environment_id)) {
            throw new \InvalidArgumentException('non-nullable environment_id cannot be null');
        }
        $this->container['environment_id'] = $environment_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets keys
     *
     * @return array<string,string>
     */
    public function getKeys()
    {
        return $this->container['keys'];
    }

    /**
     * Sets keys
     *
     * @param array<string,string> $keys keys
     *
     * @return self
     */
    public function setKeys($keys)
    {
        if (is_null($keys)) {
            throw new \InvalidArgumentException('non-nullable keys cannot be null');
        }
        $this->container['keys'] = $keys;

        return $this;
    }

    /**
     * Gets metrics
     *
     * @return \Schematic\Model\RulesengineCompanyMetric[]
     */
    public function getMetrics()
    {
        return $this->container['metrics'];
    }

    /**
     * Sets metrics
     *
     * @param \Schematic\Model\RulesengineCompanyMetric[] $metrics metrics
     *
     * @return self
     */
    public function setMetrics($metrics)
    {
        if (is_null($metrics)) {
            throw new \InvalidArgumentException('non-nullable metrics cannot be null');
        }
        $this->container['metrics'] = $metrics;

        return $this;
    }

    /**
     * Gets plan_ids
     *
     * @return string[]
     */
    public function getPlanIds()
    {
        return $this->container['plan_ids'];
    }

    /**
     * Sets plan_ids
     *
     * @param string[] $plan_ids plan_ids
     *
     * @return self
     */
    public function setPlanIds($plan_ids)
    {
        if (is_null($plan_ids)) {
            throw new \InvalidArgumentException('non-nullable plan_ids cannot be null');
        }
        $this->container['plan_ids'] = $plan_ids;

        return $this;
    }

    /**
     * Gets plan_version_ids
     *
     * @return string[]
     */
    public function getPlanVersionIds()
    {
        return $this->container['plan_version_ids'];
    }

    /**
     * Sets plan_version_ids
     *
     * @param string[] $plan_version_ids plan_version_ids
     *
     * @return self
     */
    public function setPlanVersionIds($plan_version_ids)
    {
        if (is_null($plan_version_ids)) {
            throw new \InvalidArgumentException('non-nullable plan_version_ids cannot be null');
        }
        $this->container['plan_version_ids'] = $plan_version_ids;

        return $this;
    }

    /**
     * Gets rules
     *
     * @return \Schematic\Model\RulesengineRule[]
     */
    public function getRules()
    {
        return $this->container['rules'];
    }

    /**
     * Sets rules
     *
     * @param \Schematic\Model\RulesengineRule[] $rules rules
     *
     * @return self
     */
    public function setRules($rules)
    {
        if (is_null($rules)) {
            throw new \InvalidArgumentException('non-nullable rules cannot be null');
        }
        $this->container['rules'] = $rules;

        return $this;
    }

    /**
     * Gets subscription
     *
     * @return \Schematic\Model\RulesengineSubscription|null
     */
    public function getSubscription()
    {
        return $this->container['subscription'];
    }

    /**
     * Sets subscription
     *
     * @param \Schematic\Model\RulesengineSubscription|null $subscription subscription
     *
     * @return self
     */
    public function setSubscription($subscription)
    {
        if (is_null($subscription)) {
            throw new \InvalidArgumentException('non-nullable subscription cannot be null');
        }
        $this->container['subscription'] = $subscription;

        return $this;
    }

    /**
     * Gets traits
     *
     * @return \Schematic\Model\RulesengineTrait[]
     */
    public function getTraits()
    {
        return $this->container['traits'];
    }

    /**
     * Sets traits
     *
     * @param \Schematic\Model\RulesengineTrait[] $traits traits
     *
     * @return self
     */
    public function setTraits($traits)
    {
        if (is_null($traits)) {
            throw new \InvalidArgumentException('non-nullable traits cannot be null');
        }
        $this->container['traits'] = $traits;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


