<?php
/**
 * UpdateCreditBundleDetailsRequestBody
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Schematic\Model;

use \ArrayAccess;
use \Schematic\ObjectSerializer;

/**
 * UpdateCreditBundleDetailsRequestBody Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class UpdateCreditBundleDetailsRequestBody implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'UpdateCreditBundleDetailsRequestBody';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bundle_name' => 'string',
        'expiry_type' => '\Schematic\Model\BillingCreditExpiryType',
        'expiry_unit' => '\Schematic\Model\BillingCreditExpiryUnit',
        'expiry_unit_count' => 'int',
        'price_per_unit' => 'int',
        'price_per_unit_decimal' => 'string',
        'quantity' => 'int',
        'status' => '\Schematic\Model\BillingCreditBundleStatus'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bundle_name' => null,
        'expiry_type' => null,
        'expiry_unit' => null,
        'expiry_unit_count' => null,
        'price_per_unit' => null,
        'price_per_unit_decimal' => null,
        'quantity' => null,
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bundle_name' => false,
        'expiry_type' => true,
        'expiry_unit' => true,
        'expiry_unit_count' => true,
        'price_per_unit' => false,
        'price_per_unit_decimal' => true,
        'quantity' => true,
        'status' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bundle_name' => 'bundle_name',
        'expiry_type' => 'expiry_type',
        'expiry_unit' => 'expiry_unit',
        'expiry_unit_count' => 'expiry_unit_count',
        'price_per_unit' => 'price_per_unit',
        'price_per_unit_decimal' => 'price_per_unit_decimal',
        'quantity' => 'quantity',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bundle_name' => 'setBundleName',
        'expiry_type' => 'setExpiryType',
        'expiry_unit' => 'setExpiryUnit',
        'expiry_unit_count' => 'setExpiryUnitCount',
        'price_per_unit' => 'setPricePerUnit',
        'price_per_unit_decimal' => 'setPricePerUnitDecimal',
        'quantity' => 'setQuantity',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bundle_name' => 'getBundleName',
        'expiry_type' => 'getExpiryType',
        'expiry_unit' => 'getExpiryUnit',
        'expiry_unit_count' => 'getExpiryUnitCount',
        'price_per_unit' => 'getPricePerUnit',
        'price_per_unit_decimal' => 'getPricePerUnitDecimal',
        'quantity' => 'getQuantity',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('bundle_name', $data ?? [], null);
        $this->setIfExists('expiry_type', $data ?? [], null);
        $this->setIfExists('expiry_unit', $data ?? [], null);
        $this->setIfExists('expiry_unit_count', $data ?? [], null);
        $this->setIfExists('price_per_unit', $data ?? [], null);
        $this->setIfExists('price_per_unit_decimal', $data ?? [], null);
        $this->setIfExists('quantity', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bundle_name'] === null) {
            $invalidProperties[] = "'bundle_name' can't be null";
        }
        if ((mb_strlen($this->container['bundle_name']) > 256)) {
            $invalidProperties[] = "invalid value for 'bundle_name', the character length must be smaller than or equal to 256.";
        }

        if (!is_null($this->container['expiry_unit_count']) && ($this->container['expiry_unit_count'] < 1)) {
            $invalidProperties[] = "invalid value for 'expiry_unit_count', must be bigger than or equal to 1.";
        }

        if ($this->container['price_per_unit'] === null) {
            $invalidProperties[] = "'price_per_unit' can't be null";
        }
        if (($this->container['price_per_unit'] < 0)) {
            $invalidProperties[] = "invalid value for 'price_per_unit', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['quantity']) && ($this->container['quantity'] < 1)) {
            $invalidProperties[] = "invalid value for 'quantity', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bundle_name
     *
     * @return string
     */
    public function getBundleName()
    {
        return $this->container['bundle_name'];
    }

    /**
     * Sets bundle_name
     *
     * @param string $bundle_name bundle_name
     *
     * @return self
     */
    public function setBundleName($bundle_name)
    {
        if (is_null($bundle_name)) {
            throw new \InvalidArgumentException('non-nullable bundle_name cannot be null');
        }
        if ((mb_strlen($bundle_name) > 256)) {
            throw new \InvalidArgumentException('invalid length for $bundle_name when calling UpdateCreditBundleDetailsRequestBody., must be smaller than or equal to 256.');
        }

        $this->container['bundle_name'] = $bundle_name;

        return $this;
    }

    /**
     * Gets expiry_type
     *
     * @return \Schematic\Model\BillingCreditExpiryType|null
     */
    public function getExpiryType()
    {
        return $this->container['expiry_type'];
    }

    /**
     * Sets expiry_type
     *
     * @param \Schematic\Model\BillingCreditExpiryType|null $expiry_type expiry_type
     *
     * @return self
     */
    public function setExpiryType($expiry_type)
    {
        if (is_null($expiry_type)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_type'] = $expiry_type;

        return $this;
    }

    /**
     * Gets expiry_unit
     *
     * @return \Schematic\Model\BillingCreditExpiryUnit|null
     */
    public function getExpiryUnit()
    {
        return $this->container['expiry_unit'];
    }

    /**
     * Sets expiry_unit
     *
     * @param \Schematic\Model\BillingCreditExpiryUnit|null $expiry_unit expiry_unit
     *
     * @return self
     */
    public function setExpiryUnit($expiry_unit)
    {
        if (is_null($expiry_unit)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_unit');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_unit', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expiry_unit'] = $expiry_unit;

        return $this;
    }

    /**
     * Gets expiry_unit_count
     *
     * @return int|null
     */
    public function getExpiryUnitCount()
    {
        return $this->container['expiry_unit_count'];
    }

    /**
     * Sets expiry_unit_count
     *
     * @param int|null $expiry_unit_count expiry_unit_count
     *
     * @return self
     */
    public function setExpiryUnitCount($expiry_unit_count)
    {
        if (is_null($expiry_unit_count)) {
            array_push($this->openAPINullablesSetToNull, 'expiry_unit_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expiry_unit_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($expiry_unit_count) && ($expiry_unit_count < 1)) {
            throw new \InvalidArgumentException('invalid value for $expiry_unit_count when calling UpdateCreditBundleDetailsRequestBody., must be bigger than or equal to 1.');
        }

        $this->container['expiry_unit_count'] = $expiry_unit_count;

        return $this;
    }

    /**
     * Gets price_per_unit
     *
     * @return int
     */
    public function getPricePerUnit()
    {
        return $this->container['price_per_unit'];
    }

    /**
     * Sets price_per_unit
     *
     * @param int $price_per_unit price_per_unit
     *
     * @return self
     */
    public function setPricePerUnit($price_per_unit)
    {
        if (is_null($price_per_unit)) {
            throw new \InvalidArgumentException('non-nullable price_per_unit cannot be null');
        }

        if (($price_per_unit < 0)) {
            throw new \InvalidArgumentException('invalid value for $price_per_unit when calling UpdateCreditBundleDetailsRequestBody., must be bigger than or equal to 0.');
        }

        $this->container['price_per_unit'] = $price_per_unit;

        return $this;
    }

    /**
     * Gets price_per_unit_decimal
     *
     * @return string|null
     */
    public function getPricePerUnitDecimal()
    {
        return $this->container['price_per_unit_decimal'];
    }

    /**
     * Sets price_per_unit_decimal
     *
     * @param string|null $price_per_unit_decimal price_per_unit_decimal
     *
     * @return self
     */
    public function setPricePerUnitDecimal($price_per_unit_decimal)
    {
        if (is_null($price_per_unit_decimal)) {
            array_push($this->openAPINullablesSetToNull, 'price_per_unit_decimal');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_per_unit_decimal', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['price_per_unit_decimal'] = $price_per_unit_decimal;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int|null
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int|null $quantity quantity
     *
     * @return self
     */
    public function setQuantity($quantity)
    {
        if (is_null($quantity)) {
            array_push($this->openAPINullablesSetToNull, 'quantity');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('quantity', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($quantity) && ($quantity < 1)) {
            throw new \InvalidArgumentException('invalid value for $quantity when calling UpdateCreditBundleDetailsRequestBody., must be bigger than or equal to 1.');
        }

        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets status
     *
     * @return \Schematic\Model\BillingCreditBundleStatus|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param \Schematic\Model\BillingCreditBundleStatus|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            array_push($this->openAPINullablesSetToNull, 'status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


