<?php
/**
 * ScheduledcheckoutApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Schematic\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Schematic\ApiException;
use Schematic\Configuration;
use Schematic\FormDataProcessor;
use Schematic\HeaderSelector;
use Schematic\ObjectSerializer;

/**
 * ScheduledcheckoutApi Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScheduledcheckoutApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createScheduledCheckout' => [
            'application/json',
        ],
        'getScheduledCheckout' => [
            'application/json',
        ],
        'listScheduledCheckouts' => [
            'application/json',
        ],
        'updateScheduledCheckout' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createScheduledCheckout
     *
     * Create scheduled checkout
     *
     * @param  \Schematic\Model\CreateScheduledCheckoutRequest $create_scheduled_checkout_request create_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Schematic\Model\CreateScheduledCheckoutResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError
     */
    public function createScheduledCheckout($create_scheduled_checkout_request, string $contentType = self::contentTypes['createScheduledCheckout'][0])
    {
        list($response) = $this->createScheduledCheckoutWithHttpInfo($create_scheduled_checkout_request, $contentType);
        return $response;
    }

    /**
     * Operation createScheduledCheckoutWithHttpInfo
     *
     * Create scheduled checkout
     *
     * @param  \Schematic\Model\CreateScheduledCheckoutRequest $create_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Schematic\Model\CreateScheduledCheckoutResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createScheduledCheckoutWithHttpInfo($create_scheduled_checkout_request, string $contentType = self::contentTypes['createScheduledCheckout'][0])
    {
        $request = $this->createScheduledCheckoutRequest($create_scheduled_checkout_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\CreateScheduledCheckoutResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Schematic\Model\CreateScheduledCheckoutResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\CreateScheduledCheckoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation createScheduledCheckoutAsync
     *
     * Create scheduled checkout
     *
     * @param  \Schematic\Model\CreateScheduledCheckoutRequest $create_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createScheduledCheckoutAsync($create_scheduled_checkout_request, string $contentType = self::contentTypes['createScheduledCheckout'][0])
    {
        return $this->createScheduledCheckoutAsyncWithHttpInfo($create_scheduled_checkout_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createScheduledCheckoutAsyncWithHttpInfo
     *
     * Create scheduled checkout
     *
     * @param  \Schematic\Model\CreateScheduledCheckoutRequest $create_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createScheduledCheckoutAsyncWithHttpInfo($create_scheduled_checkout_request, string $contentType = self::contentTypes['createScheduledCheckout'][0])
    {
        $returnType = '\Schematic\Model\CreateScheduledCheckoutResponse';
        $request = $this->createScheduledCheckoutRequest($create_scheduled_checkout_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createScheduledCheckout'
     *
     * @param  \Schematic\Model\CreateScheduledCheckoutRequest $create_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createScheduledCheckoutRequest($create_scheduled_checkout_request, string $contentType = self::contentTypes['createScheduledCheckout'][0])
    {

        // verify the required parameter 'create_scheduled_checkout_request' is set
        if ($create_scheduled_checkout_request === null || (is_array($create_scheduled_checkout_request) && count($create_scheduled_checkout_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_scheduled_checkout_request when calling createScheduledCheckout'
            );
        }


        $resourcePath = '/scheduled-checkout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($create_scheduled_checkout_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($create_scheduled_checkout_request));
            } else {
                $httpBody = $create_scheduled_checkout_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Schematic-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Schematic-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getScheduledCheckout
     *
     * Get scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Schematic\Model\GetScheduledCheckoutResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError
     */
    public function getScheduledCheckout($scheduled_checkout_id, string $contentType = self::contentTypes['getScheduledCheckout'][0])
    {
        list($response) = $this->getScheduledCheckoutWithHttpInfo($scheduled_checkout_id, $contentType);
        return $response;
    }

    /**
     * Operation getScheduledCheckoutWithHttpInfo
     *
     * Get scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Schematic\Model\GetScheduledCheckoutResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getScheduledCheckoutWithHttpInfo($scheduled_checkout_id, string $contentType = self::contentTypes['getScheduledCheckout'][0])
    {
        $request = $this->getScheduledCheckoutRequest($scheduled_checkout_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\GetScheduledCheckoutResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Schematic\Model\GetScheduledCheckoutResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\GetScheduledCheckoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation getScheduledCheckoutAsync
     *
     * Get scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getScheduledCheckoutAsync($scheduled_checkout_id, string $contentType = self::contentTypes['getScheduledCheckout'][0])
    {
        return $this->getScheduledCheckoutAsyncWithHttpInfo($scheduled_checkout_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getScheduledCheckoutAsyncWithHttpInfo
     *
     * Get scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getScheduledCheckoutAsyncWithHttpInfo($scheduled_checkout_id, string $contentType = self::contentTypes['getScheduledCheckout'][0])
    {
        $returnType = '\Schematic\Model\GetScheduledCheckoutResponse';
        $request = $this->getScheduledCheckoutRequest($scheduled_checkout_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getScheduledCheckout'
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getScheduledCheckoutRequest($scheduled_checkout_id, string $contentType = self::contentTypes['getScheduledCheckout'][0])
    {

        // verify the required parameter 'scheduled_checkout_id' is set
        if ($scheduled_checkout_id === null || (is_array($scheduled_checkout_id) && count($scheduled_checkout_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $scheduled_checkout_id when calling getScheduledCheckout'
            );
        }


        $resourcePath = '/scheduled-checkout/{scheduled_checkout_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($scheduled_checkout_id !== null) {
            $resourcePath = str_replace(
                '{' . 'scheduled_checkout_id' . '}',
                ObjectSerializer::toPathValue($scheduled_checkout_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Schematic-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Schematic-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listScheduledCheckouts
     *
     * List scheduled checkouts
     *
     * @param  string|null $company_id company_id (optional)
     * @param  \Schematic\Model\ScheduledCheckoutStatus|null $status status (optional)
     * @param  int|null $limit Page limit (default 100) (optional)
     * @param  int|null $offset Page offset (default 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScheduledCheckouts'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Schematic\Model\ListScheduledCheckoutsResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError
     */
    public function listScheduledCheckouts($company_id = null, $status = null, $limit = null, $offset = null, string $contentType = self::contentTypes['listScheduledCheckouts'][0])
    {
        list($response) = $this->listScheduledCheckoutsWithHttpInfo($company_id, $status, $limit, $offset, $contentType);
        return $response;
    }

    /**
     * Operation listScheduledCheckoutsWithHttpInfo
     *
     * List scheduled checkouts
     *
     * @param  string|null $company_id (optional)
     * @param  \Schematic\Model\ScheduledCheckoutStatus|null $status (optional)
     * @param  int|null $limit Page limit (default 100) (optional)
     * @param  int|null $offset Page offset (default 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScheduledCheckouts'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Schematic\Model\ListScheduledCheckoutsResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listScheduledCheckoutsWithHttpInfo($company_id = null, $status = null, $limit = null, $offset = null, string $contentType = self::contentTypes['listScheduledCheckouts'][0])
    {
        $request = $this->listScheduledCheckoutsRequest($company_id, $status, $limit, $offset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ListScheduledCheckoutsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Schematic\Model\ListScheduledCheckoutsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ListScheduledCheckoutsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation listScheduledCheckoutsAsync
     *
     * List scheduled checkouts
     *
     * @param  string|null $company_id (optional)
     * @param  \Schematic\Model\ScheduledCheckoutStatus|null $status (optional)
     * @param  int|null $limit Page limit (default 100) (optional)
     * @param  int|null $offset Page offset (default 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScheduledCheckouts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listScheduledCheckoutsAsync($company_id = null, $status = null, $limit = null, $offset = null, string $contentType = self::contentTypes['listScheduledCheckouts'][0])
    {
        return $this->listScheduledCheckoutsAsyncWithHttpInfo($company_id, $status, $limit, $offset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listScheduledCheckoutsAsyncWithHttpInfo
     *
     * List scheduled checkouts
     *
     * @param  string|null $company_id (optional)
     * @param  \Schematic\Model\ScheduledCheckoutStatus|null $status (optional)
     * @param  int|null $limit Page limit (default 100) (optional)
     * @param  int|null $offset Page offset (default 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScheduledCheckouts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listScheduledCheckoutsAsyncWithHttpInfo($company_id = null, $status = null, $limit = null, $offset = null, string $contentType = self::contentTypes['listScheduledCheckouts'][0])
    {
        $returnType = '\Schematic\Model\ListScheduledCheckoutsResponse';
        $request = $this->listScheduledCheckoutsRequest($company_id, $status, $limit, $offset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listScheduledCheckouts'
     *
     * @param  string|null $company_id (optional)
     * @param  \Schematic\Model\ScheduledCheckoutStatus|null $status (optional)
     * @param  int|null $limit Page limit (default 100) (optional)
     * @param  int|null $offset Page offset (default 0) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listScheduledCheckouts'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listScheduledCheckoutsRequest($company_id = null, $status = null, $limit = null, $offset = null, string $contentType = self::contentTypes['listScheduledCheckouts'][0])
    {



        if ($limit !== null && $limit > 250) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ScheduledcheckoutApi.listScheduledCheckouts, must be smaller than or equal to 250.');
        }
        if ($limit !== null && $limit < 0) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling ScheduledcheckoutApi.listScheduledCheckouts, must be bigger than or equal to 0.');
        }



        $resourcePath = '/scheduled-checkout';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $company_id,
            'company_id', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'ScheduledCheckoutStatus', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Schematic-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Schematic-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateScheduledCheckout
     *
     * Update scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  \Schematic\Model\UpdateScheduledCheckoutRequest $update_scheduled_checkout_request update_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Schematic\Model\UpdateScheduledCheckoutResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError
     */
    public function updateScheduledCheckout($scheduled_checkout_id, $update_scheduled_checkout_request, string $contentType = self::contentTypes['updateScheduledCheckout'][0])
    {
        list($response) = $this->updateScheduledCheckoutWithHttpInfo($scheduled_checkout_id, $update_scheduled_checkout_request, $contentType);
        return $response;
    }

    /**
     * Operation updateScheduledCheckoutWithHttpInfo
     *
     * Update scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  \Schematic\Model\UpdateScheduledCheckoutRequest $update_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \Schematic\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Schematic\Model\UpdateScheduledCheckoutResponse|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError|\Schematic\Model\ApiError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateScheduledCheckoutWithHttpInfo($scheduled_checkout_id, $update_scheduled_checkout_request, string $contentType = self::contentTypes['updateScheduledCheckout'][0])
    {
        $request = $this->updateScheduledCheckoutRequest($scheduled_checkout_id, $update_scheduled_checkout_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\UpdateScheduledCheckoutResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
                case 500:
                    return $this->handleResponseWithDataType(
                        '\Schematic\Model\ApiError',
                        $request,
                        $response,
                    );
            }



            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Schematic\Model\UpdateScheduledCheckoutResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\UpdateScheduledCheckoutResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Schematic\Model\ApiError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }


            throw $e;
        }
    }

    /**
     * Operation updateScheduledCheckoutAsync
     *
     * Update scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  \Schematic\Model\UpdateScheduledCheckoutRequest $update_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateScheduledCheckoutAsync($scheduled_checkout_id, $update_scheduled_checkout_request, string $contentType = self::contentTypes['updateScheduledCheckout'][0])
    {
        return $this->updateScheduledCheckoutAsyncWithHttpInfo($scheduled_checkout_id, $update_scheduled_checkout_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateScheduledCheckoutAsyncWithHttpInfo
     *
     * Update scheduled checkout
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  \Schematic\Model\UpdateScheduledCheckoutRequest $update_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateScheduledCheckoutAsyncWithHttpInfo($scheduled_checkout_id, $update_scheduled_checkout_request, string $contentType = self::contentTypes['updateScheduledCheckout'][0])
    {
        $returnType = '\Schematic\Model\UpdateScheduledCheckoutResponse';
        $request = $this->updateScheduledCheckoutRequest($scheduled_checkout_id, $update_scheduled_checkout_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateScheduledCheckout'
     *
     * @param  string $scheduled_checkout_id scheduled_checkout_id (required)
     * @param  \Schematic\Model\UpdateScheduledCheckoutRequest $update_scheduled_checkout_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateScheduledCheckout'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateScheduledCheckoutRequest($scheduled_checkout_id, $update_scheduled_checkout_request, string $contentType = self::contentTypes['updateScheduledCheckout'][0])
    {

        // verify the required parameter 'scheduled_checkout_id' is set
        if ($scheduled_checkout_id === null || (is_array($scheduled_checkout_id) && count($scheduled_checkout_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $scheduled_checkout_id when calling updateScheduledCheckout'
            );
        }

        // verify the required parameter 'update_scheduled_checkout_request' is set
        if ($update_scheduled_checkout_request === null || (is_array($update_scheduled_checkout_request) && count($update_scheduled_checkout_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $update_scheduled_checkout_request when calling updateScheduledCheckout'
            );
        }


        $resourcePath = '/scheduled-checkout/{scheduled_checkout_id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($scheduled_checkout_id !== null) {
            $resourcePath = str_replace(
                '{' . 'scheduled_checkout_id' . '}',
                ObjectSerializer::toPathValue($scheduled_checkout_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($update_scheduled_checkout_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($update_scheduled_checkout_request));
            } else {
                $httpBody = $update_scheduled_checkout_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Schematic-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Schematic-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
