<?php
/**
 * PlanGroupDetailResponseDataTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.10.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Schematic\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PlanGroupDetailResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description The returned resource
 * @package     Schematic
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PlanGroupDetailResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PlanGroupDetailResponseData"
     */
    public function testPlanGroupDetailResponseData()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "add_ons"
     */
    public function testPropertyAddOns()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_plan"
     */
    public function testPropertyDefaultPlan()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "default_plan_id"
     */
    public function testPropertyDefaultPlanId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "plans"
     */
    public function testPropertyPlans()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trial_days"
     */
    public function testPropertyTrialDays()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trial_payment_method_required"
     */
    public function testPropertyTrialPaymentMethodRequired()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
