<?php
/**
 * UpdateCatalogConfigurationRequestBodyTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Schematic\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UpdateCatalogConfigurationRequestBodyTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateCatalogConfigurationRequestBody
 * @package     Schematic
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UpdateCatalogConfigurationRequestBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UpdateCatalogConfigurationRequestBody"
     */
    public function testUpdateCatalogConfigurationRequestBody()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_plan_cta_text"
     */
    public function testPropertyCustomPlanCtaText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_plan_cta_url"
     */
    public function testPropertyCustomPlanCtaUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_plan_price_text"
     */
    public function testPropertyCustomPlanPriceText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_plans_visible"
     */
    public function testPropertyCustomPlansVisible()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ordered_add_ons"
     */
    public function testPropertyOrderedAddOns()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ordered_bundles"
     */
    public function testPropertyOrderedBundles()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ordered_plans"
     */
    public function testPropertyOrderedPlans()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pricing_model"
     */
    public function testPropertyPricingModel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pricing_url"
     */
    public function testPropertyPricingUrl()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
