<?php
/**
 * PlanmigrationsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: engineering@schematichq.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Schematic\Test\Api;

use \Schematic\Configuration;
use \Schematic\ApiException;
use \Schematic\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PlanmigrationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlanmigrationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for countCompanyMigrations
     *
     * Count company migrations.
     *
     */
    public function testCountCompanyMigrations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countMigrations
     *
     * Count migrations.
     *
     */
    public function testCountMigrations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createMigration
     *
     * Create migration.
     *
     */
    public function testCreateMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getMigration
     *
     * Get migration.
     *
     */
    public function testGetMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCompanyMigrations
     *
     * List company migrations.
     *
     */
    public function testListCompanyMigrations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMigrations
     *
     * List migrations.
     *
     */
    public function testListMigrations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for previewMigration
     *
     * Preview migration.
     *
     */
    public function testPreviewMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retryCompanyMigration
     *
     * Retry company migration.
     *
     */
    public function testRetryCompanyMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for retryMigration
     *
     * Retry migration.
     *
     */
    public function testRetryMigration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
