<?php
/**
 * SchematicApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Schematic API
 *
 * Schematic API
 *
 * The version of the OpenAPI document: 0.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Schematic\Test\Api;

use \Schematic\Configuration;
use \Schematic\ApiException;
use \Schematic\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * SchematicApiTest Class Doc Comment
 *
 * @category Class
 * @package  Schematic
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SchematicApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for checkFlag
     *
     * Check flag.
     *
     */
    public function testCheckFlag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for checkFlags
     *
     * Check flags.
     *
     */
    public function testCheckFlags()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countApiKeys
     *
     * Count api keys.
     *
     */
    public function testCountApiKeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countApiRequests
     *
     * Count api requests.
     *
     */
    public function testCountApiRequests()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countCompaniesAudience
     *
     * Count Companies audience.
     *
     */
    public function testCountCompaniesAudience()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countEventTypes
     *
     * Count event types.
     *
     */
    public function testCountEventTypes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countEvents
     *
     * Count events.
     *
     */
    public function testCountEvents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countFlagChecks
     *
     * Count flag checks.
     *
     */
    public function testCountFlagChecks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countFlagValues
     *
     * Count flag values.
     *
     */
    public function testCountFlagValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for countUsersAudience
     *
     * Count Users audience.
     *
     */
    public function testCountUsersAudience()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createApiKey
     *
     * Create api key.
     *
     */
    public function testCreateApiKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCompany
     *
     * Create company.
     *
     */
    public function testCreateCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createCompanyMembership
     *
     * Create company membership.
     *
     */
    public function testCreateCompanyMembership()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEnvironment
     *
     * Create environment.
     *
     */
    public function testCreateEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createEvent
     *
     * Create event.
     *
     */
    public function testCreateEvent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFeature
     *
     * Create feature.
     *
     */
    public function testCreateFeature()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createFlag
     *
     * Create flag.
     *
     */
    public function testCreateFlag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createPlan
     *
     * Create plan.
     *
     */
    public function testCreatePlan()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createRule
     *
     * Create rule.
     *
     */
    public function testCreateRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createUser
     *
     * Create user.
     *
     */
    public function testCreateUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteApiKey
     *
     * Delete api key.
     *
     */
    public function testDeleteApiKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteCompanyMembership
     *
     * Delete company membership.
     *
     */
    public function testDeleteCompanyMembership()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEnvironment
     *
     * Delete environment.
     *
     */
    public function testDeleteEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFeature
     *
     * Delete feature.
     *
     */
    public function testDeleteFeature()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteFlag
     *
     * Delete flag.
     *
     */
    public function testDeleteFlag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletePlan
     *
     * Delete plan.
     *
     */
    public function testDeletePlan()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiKey
     *
     * Get api key.
     *
     */
    public function testGetApiKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getApiRequest
     *
     * Get api request.
     *
     */
    public function testGetApiRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompaniesAudience
     *
     * Get Companies audience.
     *
     */
    public function testGetCompaniesAudience()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCompany
     *
     * Get company.
     *
     */
    public function testGetCompany()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironment
     *
     * Get environment.
     *
     */
    public function testGetEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEvent
     *
     * Get event.
     *
     */
    public function testGetEvent()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEventType
     *
     * Get event type.
     *
     */
    public function testGetEventType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFeature
     *
     * Get feature.
     *
     */
    public function testGetFeature()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFlag
     *
     * Get flag.
     *
     */
    public function testGetFlag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getFlagCheck
     *
     * Get flag check.
     *
     */
    public function testGetFlagCheck()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getPlan
     *
     * Get plan.
     *
     */
    public function testGetPlan()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRule
     *
     * Get rule.
     *
     */
    public function testGetRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUser
     *
     * Get user.
     *
     */
    public function testGetUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUsersAudience
     *
     * Get Users audience.
     *
     */
    public function testGetUsersAudience()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for latestFlagChecks
     *
     * Latest flag checks.
     *
     */
    public function testLatestFlagChecks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiKeys
     *
     * List api keys.
     *
     */
    public function testListApiKeys()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listApiRequests
     *
     * List api requests.
     *
     */
    public function testListApiRequests()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCompanies
     *
     * List companies.
     *
     */
    public function testListCompanies()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCompanyMemberships
     *
     * List company memberships.
     *
     */
    public function testListCompanyMemberships()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listCompanyPlans
     *
     * List company plans.
     *
     */
    public function testListCompanyPlans()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEventTypes
     *
     * List event types.
     *
     */
    public function testListEventTypes()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listEvents
     *
     * List events.
     *
     */
    public function testListEvents()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFeatures
     *
     * List features.
     *
     */
    public function testListFeatures()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFlagChecks
     *
     * List flag checks.
     *
     */
    public function testListFlagChecks()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFlagValues
     *
     * List flag values.
     *
     */
    public function testListFlagValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listFlags
     *
     * List flags.
     *
     */
    public function testListFlags()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMetricCounts
     *
     * List metric counts.
     *
     */
    public function testListMetricCounts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listMetricCountsHourly
     *
     * List metric counts hourly.
     *
     */
    public function testListMetricCountsHourly()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPlans
     *
     * List plans.
     *
     */
    public function testListPlans()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listUsers
     *
     * List users.
     *
     */
    public function testListUsers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateApiKey
     *
     * Update api key.
     *
     */
    public function testUpdateApiKey()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEntityTraitDefinition
     *
     * Update entity trait definition.
     *
     */
    public function testUpdateEntityTraitDefinition()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateEnvironment
     *
     * Update environment.
     *
     */
    public function testUpdateEnvironment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateFeature
     *
     * Update feature.
     *
     */
    public function testUpdateFeature()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateFlag
     *
     * Update flag.
     *
     */
    public function testUpdateFlag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePlan
     *
     * Update plan.
     *
     */
    public function testUpdatePlan()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updatePlanAudience
     *
     * Update plan audience.
     *
     */
    public function testUpdatePlanAudience()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRule
     *
     * Update rule.
     *
     */
    public function testUpdateRule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for upsertBillingPeriod
     *
     * Upsert billing period.
     *
     */
    public function testUpsertBillingPeriod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
